from app.models import Email, EmailThread


def test_get_drafts_empty(client):
    response = client.get("/api/v1/drafts")
    assert response.status_code == 200
    assert response.json() == []


def test_save_draft(client, db_session):
    # Create a dummy thread and email first so the foreign keys resolve
    thread = EmailThread(gmail_account_id=1, gmail_thread_id="thread_test")
    db_session.add(thread)
    db_session.commit()

    email = Email(
        thread_id=thread.id,
        gmail_message_id="msg_test",
        sender="bob@example.com",
        recipients="test@example.com",
        subject="Hello Test",
        direction="incoming",
        body="<p>Test body</p>",
        cleaned_body="Test body",
        snippet="Test body",
    )
    db_session.add(email)
    db_session.commit()

    draft_payload = {
        "subject": "Re: Hello Test",
        "body": "This is a test draft generated by the AI.",
        "original_email_id": email.id,
    }

    response = client.post("/api/v1/drafts", json=draft_payload)
    assert response.status_code == 200

    data = response.json()
    assert "id" in data
    assert data["subject"] == "Re: Hello Test"
    assert data["body"] == "This is a test draft generated by the AI."


def test_get_drafts_after_save(client):
    response = client.get("/api/v1/drafts")
    assert response.status_code == 200

    data = response.json()
    assert len(data) == 1
    assert data[0]["subject"] == "Re: Hello Test"
