"""add_performance_indexes

Revision ID: 4a3e04daadc2
Revises: 4bb93dd23f1d
Create Date: 2026-08-20 13:30:27.783390

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a3e04daadc2"
down_revision: str | Sequence[str] | None = "4bb93dd23f1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_email_chunks_email_id"), "email_chunks", ["email_id"], unique=False
    )
    op.create_index(
        "ix_email_chunks_embedding_hnsw",
        "email_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_emails_thread_id"), "emails", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_emails_thread_id"), table_name="emails")
    op.drop_index(
        "ix_email_chunks_embedding_hnsw",
        table_name="email_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_email_chunks_email_id"), table_name="email_chunks")
    # ### end Alembic commands ###
