"""remove unique constraint from user_id in gmail_accounts

Revision ID: 4bb93dd23f1d
Revises: 705a9079f906
Create Date: 2026-08-19 21:25:30.625848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb93dd23f1d'
down_revision: Union[str, Sequence[str], None] = '705a9079f906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('gmail_accounts_user_id_key'), 'gmail_accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('gmail_accounts_user_id_key'), 'gmail_accounts', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
