"""add_profile_fields

Revision ID: 705a9079f906
Revises: 5fc004b77b80
Create Date: 2026-08-19 19:45:55.622581

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "705a9079f906"
down_revision: str | Sequence[str] | None = "5fc004b77b80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gmail_accounts", sa.Column("name", sa.String(), nullable=True))
    op.add_column(
        "gmail_accounts", sa.Column("picture_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gmail_accounts", "picture_url")
    op.drop_column("gmail_accounts", "name")
    # ### end Alembic commands ###
